### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by kimchanhyung98** [shlifedev/TarkovApp#4]
**유의적 버전**
버전 번호를 어떻게 정하고 올려야 하는지를 명시하는 규칙과 요구사항을 제안.

- 현재 : 0.0.2 -> 0.3
- 참고 링크 : [Semantic Versioning 2.0.0-ko2](https://semver.org/lang/ko/)

**Comment by shlifedev** [comment]
0.0.3 is right thx
